ef add_product():
    popup = Toplevel(POS)
    popup.title("Add Product")
    popup.geometry("700x500")
    popup.grab_set()
    Label(popup,text="Enter Product ID").pack()
    product = Entry(popup)
    product.pack()
    Label(popup,text="Enter Product Name").pack()
    name = Entry(popup)
    name.pack()
    Label(popup,text="Enter Product Category").pack()
    category = Entry(popup)
    category.pack()
    Label(popup,text="Enter Product Price").pack()
    price = Entry(popup)
    price.pack()
    Label(popup,text="Enter Product Stock/s").pack()
    stocks = Entry(popup)
    stocks.pack()
    Label(popup,text="Enter Product Reorder lvl").pack()
    reorder = Entry(popup)
    reorder.pack()
    def submit():
        try:
            Backend.add_new(product.get(),name.get(),category.get(),price.get(),stocks.get(),reorder.get())
            product.delete(0,END)
            name.delete(0,END)
            category.delete(0,END)
            price.delete(0,END)
            stocks.delete(0,END)
            reorder.delete(0,END)
            popup.destroy()
        except ValueError:
            messagebox.showwarning("Warning", "pls enter integers/decimals on price,stocks and reorder lvl")
            price.delete(0,END)
            stocks.delete(0,END)
            reorder.delete(0,END)
    def exit():
        popup.destroy()
    Button(popup,text="Submit",command=submit).pack()
    Button(popup,text="Exit",command=exit).pack()

